db:
  image: mongo
  expose:
    - "27017"
  command: "--smallfiles --logpath=/dev/null"
web:
  build: .
  command: node app.js
  volumes:
    - .:/code
  ports:
    - "3000:3000"
  links:
    - db
  environment:
    PORT: 3000
    DB_PORT: 27017
